[package]
name = "complex_numbers"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "*"
tokio = { version = "*", features = ["full"] }
